module.exports = [
  'build/',
  '.agents/',
  '.codex/',
  '.specify/',
  'tools/',
  'specs/',
  'docs/',
  'packages/jev-ultrafast/src/jev_ultrafast/',
  'scripts/vendor/',
  'plugins/code/hooks/',
  'plugins/code/tests/hooks.test.js',
  'plugins/work/skills/quarto-authoring/',
  '**/.venv/',
];
